/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-28 11:25:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import hk.ust.cse.comp4321.project.retrieval.Retriever;
import hk.ust.cse.comp4321.project.crawl.DocumentRecord;
import org.apache.commons.lang3.tuple.Pair;
import java.util.*;
import java.util.stream.Collectors;

public final class query_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("hk.ust.cse.comp4321.project.crawl.DocumentRecord");
    _jspx_imports_classes.add("org.apache.commons.lang3.tuple.Pair");
    _jspx_imports_classes.add("java.util.stream.Collectors");
    _jspx_imports_classes.add("hk.ust.cse.comp4321.project.retrieval.Retriever");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Search Results</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background-color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 20px 30px;\n");
      out.write("            border-bottom: 1px solid #ebebeb;\n");
      out.write("            background-color: #fff;\n");
      out.write("            position: sticky;\n");
      out.write("            top: 0;\n");
      out.write("            z-index: 100;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo {\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #4285f4;\n");
      out.write("            margin-right: 30px;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-form {\n");
      out.write("            display: flex;\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 650px;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-input {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px 20px;\n");
      out.write("            font-size: 24px;\n");
      out.write("            border: 1px solid #dfe1e5;\n");
      out.write("            border-radius: 24px;\n");
      out.write("            outline: none;\n");
      out.write("            box-shadow: 0 1px 3px rgba(32,33,36,0.1);\n");
      out.write("            transition: box-shadow 0.2s;\n");
      out.write("        }\n");
      out.write("        .search-input:focus {\n");
      out.write("            box-shadow: 0 1px 6px rgba(32,33,36,0.28);\n");
      out.write("            border-color: #dfe1e5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-button {\n");
      out.write("            position: absolute;\n");
      out.write("            right: 15px;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            font-size: 24px;\n");
      out.write("            color: #4285f4;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .main-content {\n");
      out.write("            padding: 30px 50px;\n");
      out.write("            max-width: 1000px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    ");

        String query = request.getParameter("q");
        PriorityQueue<Pair<Double, DocumentRecord>> result = null;
        double durationSeconds = 0.0;
        int totalResults = 0;

        if (query != null && !query.trim().isEmpty()) {
            long startTime = System.nanoTime();
            result = Retriever.search(query);
            long endTime = System.nanoTime();
            durationSeconds = (endTime - startTime) / 1_000_000_000.0;

            if (result != null) {
                totalResults = result.size();
            }
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"top-bar\">\n");
      out.write("        <a href=\"index.jsp\" class=\"logo\">HKUST PowerSearch</a> <form class=\"search-form\" action=\"\" method=\"get\">\n");
      out.write("            <input type=\"text\" name=\"q\" class=\"search-input\"\n");
      out.write("                   value=\"");
      out.print( (query != null) ? query : "" );
      out.write("\"\n");
      out.write("                   placeholder=\"Search anything...\" />\n");
      out.write("            <button type=\"submit\" class=\"search-button\"><svg focusable=\"false\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"20\" height=\"20\" fill=\"#9aa0a6\">\n");
      out.write("                                                                        <path d=\"M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z\"></path>\n");
      out.write("                                                                    </svg>\n");
      out.write("</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"main-content\">\n");
      out.write("\n");
      out.write("        ");
 if (query != null && !query.trim().isEmpty()) { 
      out.write("\n");
      out.write("            <div style=\"color: #70757a; font-size: 1.4em; margin-bottom: 20px;\">\n");
      out.write("            About ");
      out.print( totalResults );
      out.write(" results (");
      out.print( String.format("%.3f", durationSeconds) );
      out.write(" seconds)\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        ");

            if (result != null && !result.isEmpty()) {
                int i = 0;
                while (!result.isEmpty() && i < 50) {
                    i++;
                    Pair<Double, DocumentRecord> pair = result.poll();
                    DocumentRecord this_result = pair.getRight();

                    List<Map.Entry<String, Long>> topKeywords = this_result.bodyTermFrequencies().entrySet().stream()
                        .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
                        .limit(5)
                        .collect(Collectors.toList());

                    double score = pair.getLeft();
                    String label = "";
                    String color = "";

                    if (score >= 0.8) {
                        label = "Very Relevant| 🥰";
                        color = "#28a745";
                    } else if (score >= 0.5) {
                        label = "Relevant| 😄";
                        color = "#17a2b8";
                    } else if (score >= 0.3) {
                        label = "Low Relevant| 😙";
                        color = "#ffc107";
                    } else if (score > 0) {
                        label = "Very Low Relevant| 🤨";
                        color = "#fd7e14";
                    } else {
                        score = 0.0;
                        label = "Not Relevant| 😑";
                        color = "#dc3545";
                    }
        
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"card\" style=\"border: 1px solid #ddd; padding: 25px; margin-bottom: 20px; border-radius: 8px;\">\n");
      out.write("                <div class=\"title\">\n");
      out.write("                    Page ");
      out.print( i );
      out.write(":\n");
      out.write("                    <a href=\"");
      out.print( this_result.url() );
      out.write("\" style=\"font-weight: bold; color: #1a0dab; text-decoration: none; font-size: 26px;\">\n");
      out.write("                        ");
      out.print( (this_result.title() == null || this_result.title().isEmpty()) ? "Untitled" : this_result.title() );
      out.write("\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <p style=\"margin: 5px 0;\">\n");
      out.write("                    <a href=\"");
      out.print( this_result.url() );
      out.write("\"  style=\"color: #006621; text-decoration: none; font-size: 21px;\">\n");
      out.write("                        ");
      out.print( this_result.url() );
      out.write("\n");
      out.write("                    </a>\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <p style=\"font-weight: bold; font-size: 21px;\">\n");
      out.write("                    Similarity Rate:\n");
      out.write("                    <span style=\"color: ");
      out.print( color );
      out.write(";\">\n");
      out.write("                        ");
      out.print( String.format("%.4f", score) );
      out.write(' ');
      out.write('(');
      out.print( label.replace("|", ")") );
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <p style=\"font-size: 21px; color: #555;\">\n");
      out.write("                    Last mod. date: ");
      out.print( this_result.lastModificationTimestamp().toString().replace("T", " ") );
      out.write(" | Size: ");
      out.print( this_result.pageSize() );
      out.write(" Bytes\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <div class=\"keywords\" style=\"font-size: 21px;\">\n");
      out.write("                    <strong>Top Keywords:</strong>\n");
      out.write("                    ");
 for (Map.Entry<String, Long> entry : topKeywords) { 
      out.write("\n");
      out.write("                        <span style=\"background:#f1f3f4; padding:3px 8px; margin-right:5px; border-radius:12px; font-size: 18px; display: inline-block; margin-top: 5px;\">\n");
      out.write("                            ");
      out.print( entry.getKey() );
      out.write(' ');
      out.write('(');
      out.print( entry.getValue() );
      out.write(")\n");
      out.write("                        </span>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div style=\"font-size: 19px; margin-top: 15px; color: #555;\">\n");
      out.write("                    <div>\n");
      out.write("                        <strong>Parent URLs:</strong><br>\n");
      out.write("                        ");
      out.print( this_result.parentURLs().stream()
                            .map(url -> "<a href='" + url + "'  style='color: #006621; text-decoration: none;'>" + url + "</a>")
                            .collect(Collectors.joining("<br>"))
                        );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div style=\"margin-top: 10px;\">\n");
      out.write("                        <strong>Child URLs:</strong><br>\n");
      out.write("                        ");
      out.print( this_result.childURLs().stream()
                            .map(url -> "<a href='" + url + "'  style='color: #006621; text-decoration: none;'>" + url + "</a>")
                            .collect(Collectors.joining("<br>"))
                        );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        ");

                }
            } else if (query != null && !query.trim().isEmpty()) {
        
      out.write("\n");
      out.write("            <p>No results found for \"<strong>");
      out.print( query );
      out.write("</strong>\".</p>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
